### PR TITLE
chore: update ipfs

### PR DESCRIPTION
**Pull request by alanshaw**

### CODE REVIEW

**Review by vasco-santos — COMMENTED** [review]
LGTM! I tried the example and it works as expected 🚀 

Will wait for the final release to merge this

**Comment by alanshaw** [comment]
Can has merge and release @vasco-santos 🙏

**Comment by vasco-santos** [comment]
I am seeing an issue with the tests. Looking into it

**Comment by vasco-santos** [comment]
It was a bad time from CI apparently, everything looks good now

**Review by vasco-santos — APPROVED** [review]

**Pull request merged**
