### PR TITLE
preparations for js-ipfs 0.36

### PR DESCRIPTION
**Pull request by olizilla**
run the CI tests with ipfs@0.36.0-rc.0

of note, I'm seeing test failures locally on master as well as with
the latest ipfs 0.36 rc, so I'm sharing this PR to trigger CI to
see if it's just an issue on my machine.

see: https://github.com/ipfs/js-ipfs/issues/2024

### CODE REVIEW

**Comment by olizilla** [comment]
@alanshaw of note the tests are **not** passing for service-worker-gateway on 0.36.0-rc.0, but they are aren't passing on master with 0.35.0 today either.

**Comment by olizilla** [comment]
it's just timeouts trying to fetch remote content so far, so may be caused by network conditions beyond the tests.

**Comment by olizilla** [comment]
@vasco-santos do you have a moment to take a look at why the tests aren't passing?

**Comment by olizilla** [comment]
~hmm it looks like just bumping the timeouts up is the answer... which isn't great news.~ 
nope, spoke to soon, bunping it locally to `150000ms` didn't help.

**Comment by vasco-santos** [comment]
@olizilla thanks for putting this together, I will have a look!

**Review by vasco-santos — APPROVED** [review]
It is good now. The `ipfs-http-response` module needed to be updated as well, in order to provide the correct data do the `service-worker-gateway`

**Pull request merged**
