### PR TITLE
Change gateway CID matcher to exclude URL fragments & queries

### PR DESCRIPTION
**Pull request by antimatter15**
Currently js.ipfs.io breaks when one tries to reload Peerpad because it stores information in the URL fragment (for [example](https://js.ipfs.io/ipfs/QmfQiRPTxVTT31ecDMAcUgTSTDt2HdPHKTuDWnD7T689oi/index.html#)) (#blah) section of the URL, which this gateway tries to resolve as part of the IPFS path. 

This makes the behavior consistent with the other [gateways](https://gateway.ipfs.io/ipfs/QmfQiRPTxVTT31ecDMAcUgTSTDt2HdPHKTuDWnD7T689oi/index.html#) which ignore query strings and fragments.

### CODE REVIEW

**Review by vasco-santos — APPROVED** [review]
SGTM!
Thanks

**Review by vasco-santos — CHANGES_REQUESTED** [review]
Thanks!
Can you add a test for this?

In addition, can you change the commit message to get the CI green again?

**Comment by antimatter15** [comment]
Got all the checks green and added tests!

**Review by vasco-santos — APPROVED** [review]
Thanks

**Pull request merged**
